#!/usr/bin/env python3
"""Adds "The Company Story" to each company already written to
docs/earnings/data.json by build_public.py — an 11-question qualitative
framework (what it does, who buys it, the moat, leadership, growth
potential, risk, what you're paying, market cap, the 5-10 year case, and
real risk/reward) that matters more to this tracker's reader than the
numeric good/bad/ugly gates, and explicitly more than the share price,
which never appears anywhere in this section.

Same split as write_stories.py and update_position_trackers.py: anything
computable from real data is computed in Python and handed to the model as
a fact it must use as-is, never asked to reproduce or invent. Two of the
11 answers are never generated by the model at all:
  - #5 (insider ownership) is a fixed string. There's no free, keyless,
    reliable source for this, and the alternative to admitting that is a
    model quietly guessing a plausible-sounding percentage — which is
    exactly the kind of fabrication this tracker is built to avoid.
  - #9 (market cap) is formatted directly from sec_data.get_market_cap(),
    already fetched into company["valuation"] by build_public.py. It's a
    real number; there's nothing for the model to add.
The remaining 9 (business model, customers, moat, leadership, growth,
risk, valuation-vs-quality, the 5-10yr case, and risk/reward) are
fundamentally qualitative — no numeric endpoint answers "what's the
moat" — so those come from Claude, grounded in the real valuation
multiples and revenue/margin trend already computed, with an explicit
instruction not to invent its own numbers.

Usage: write_company_stories.py [OLD_DATA_JSON]
  Same pre-rebuild snapshot write_stories.py takes. A company whose
  period_end hasn't changed keeps its existing Company Story rather than
  paying for a fresh Claude call — this is long-horizon, business-quality
  narrative, not something that should change because the market cap
  ticked between two hourly runs.
"""

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from dotenv import load_dotenv

from write_stories import call_claude

ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = ROOT.parent
DATA_PATH = REPO_ROOT / "docs" / "earnings" / "data.json"

load_dotenv(REPO_ROOT / ".env")

# Numbered to match the user-facing order 1-11; 5 and 9 are deliberately
# absent here since the model is never asked about them (see module docstring).
QUESTIONS = [
    (1, "What does the company actually do — its business model, in plain language"),
    (2, "Who are its customers"),
    (3, "Why do customers buy from this company instead of the competition — "
        "the actual competitive edge or moat"),
    (4, "Who is in charge — the CEO and leadership"),
    (6, "What is the growth potential of the business"),
    (7, "What risks come with investing in this business"),
    (8, "What valuation is being paid for the business today, in terms of the "
        "multiple relative to its growth and quality — not the share price"),
    (10, "What could the market cap realistically be in five to ten years, "
         "and what would have to be true for that"),
    (11, "How much could an investor make if right, and how much could be "
         "lost if wrong — a real risk/reward framing, not just upside"),
]

LABELS = {
    1: "What it does", 2: "Who its customers are", 3: "Competitive edge",
    4: "Leadership", 5: "Insider ownership", 6: "Growth potential",
    7: "Risks", 8: "What you're paying", 9: "Market cap today",
    10: "The 5-10 year case", 11: "Risk / reward",
}

INSIDER_OWNERSHIP_ANSWER = (
    "Requires manual research — there's no free, keyless, reliable source for insider "
    "ownership percentage. Check the company's most recent DEF 14A proxy statement on SEC "
    "EDGAR (the \"Security Ownership of Certain Beneficial Owners and Management\" table) "
    "for the real number."
)


def _fmt_money(v):
    if v is None:
        return None
    a = abs(v)
    if a >= 1e12:
        return f"${v / 1e12:.2f}T"
    if a >= 1e9:
        return f"${v / 1e9:.1f}B"
    if a >= 1e6:
        return f"${v / 1e6:.1f}M"
    return f"${v:,.0f}"


def _market_cap_answer(valuation):
    mc = (valuation or {}).get("market_cap")
    if mc is None:
        return "Not available this run — Nasdaq's quote data didn't return for this ticker."
    return (f"{_fmt_money(mc)}, from Nasdaq's public quote data — the market's price on the "
            f"whole business, not a per-share number.")


def build_prompt(company):
    val = company.get("valuation") or {}
    trend = company.get("trend", {})

    facts = "\n".join([
        f"Company: {company['ticker']} ({company.get('description', '')})",
        f"Trailing P/E: {val.get('pe_ttm') if val.get('pe_ttm') is not None else 'not available (trailing net loss, or missing data)'}",
        f"EV/EBITDA (trailing): {val.get('ev_ebitda_ttm') if val.get('ev_ebitda_ttm') is not None else 'not available (missing or negative EBITDA)'}",
        f"Market cap: {_fmt_money(val.get('market_cap')) or 'not available'}",
        f"Revenue growth streak: {trend.get('revenue_growth_streak', 0)} straight quarters",
        f"Gross margin expansion streak: {trend.get('margin_expansion_streak', 0)} straight quarters",
        "Red flags: " + ("; ".join(
            f"[{f['severity'].upper()}] {f['flag']}: {f['detail']}"
            for f in company.get("red_flags", [])) or "none"),
    ])

    questions_block = "\n".join(f"{n}. {q}" for n, q in QUESTIONS)

    return f"""You are building a qualitative "Company Story" for a personal investing tracker \
read by someone who explicitly does not care about the share price — only whether this is a \
good business, understood on its own terms, and what it's worth as a whole company.

Real facts about this company — use these numbers exactly as given. Do not recompute, \
adjust, or invent your own valuation multiple, growth rate, or market cap; if a fact below \
says "not available," say so plainly rather than guessing at a number:

{facts}

Answer these {len(QUESTIONS)} questions, in this exact order, drawing on your own knowledge \
of the business for anything the facts above don't cover. Each answer: 1-3 sentences, direct \
and specific, no filler, no investment recommendation (explain, don't advise). For the \
leadership question, say plainly this is from general knowledge and may be out of date if \
there's been a very recent change. For the valuation question, cite ONLY the trailing P/E \
and EV/EBITDA given above — never a different multiple.

Reply in exactly this format, one answer per line, each prefixed by its number and a period \
(a multi-sentence answer stays on one line, no line breaks inside an answer):

{questions_block}
"""


def _parse_reply(text, expected_numbers):
    answers = {}
    for line in text.splitlines():
        m = re.match(r"^\s*(\d{1,2})\.\s+(\S.*)$", line)
        if m and int(m.group(1)) in expected_numbers:
            answers[int(m.group(1))] = m.group(2).strip()
    return answers


def build_company_story(company, api_key):
    expected = {n for n, _ in QUESTIONS}
    reply = call_claude(build_prompt(company), api_key)
    parsed = _parse_reply(reply, expected)

    story = []
    for n in range(1, 12):
        if n == 5:
            answer = INSIDER_OWNERSHIP_ANSWER
        elif n == 9:
            answer = _market_cap_answer(company.get("valuation"))
        else:
            answer = parsed.get(n, "")
        story.append({"n": n, "label": LABELS[n], "answer": answer})
    return story


def _load_old_stories(path):
    """ticker -> (period_end, company_story) from the previous run, so an
    unchanged company keeps its existing Company Story. Note this also
    keeps its old #9 (market cap) and #8 (valuation) text frozen until the
    next new quarter — acceptable here since this section is about
    multi-year business quality, not tracking valuation drift day to day;
    see module docstring."""
    if not path:
        return {}
    p = Path(path)
    if not p.exists():
        return {}
    data = json.loads(p.read_text())
    return {
        c["ticker"]: (c.get("period_end"), c["company_story"])
        for c in data.get("companies", [])
        if c.get("company_story")
    }


def main():
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        print("ANTHROPIC_API_KEY not set — skipping Company Story sections "
              "(the rest of the app still ships).")
        return 0

    if not DATA_PATH.exists():
        print(f"{DATA_PATH} doesn't exist — run build_public.py first.", file=sys.stderr)
        return 1

    old_stories = _load_old_stories(sys.argv[1] if len(sys.argv) > 1 else None)
    data = json.loads(DATA_PATH.read_text())
    wrote = reused = 0

    for company in data.get("companies", []):
        if company.get("error") or company.get("insufficient_data"):
            continue

        old = old_stories.get(company["ticker"])
        if old and old[0] == company["period_end"]:
            company["company_story"] = old[1]
            reused += 1
            continue

        try:
            company["company_story"] = build_company_story(company, api_key)
            wrote += 1
            print(f"  {company['ticker']}: wrote Company Story")
        except Exception as e:
            print(f"  {company['ticker']}: Company Story failed — {e}")
            # Leave the company without a company_story key — the card
            # already renders fine without this section present.

    DATA_PATH.write_text(json.dumps(data, indent=2) + "\n")
    print(f"Wrote {wrote} new Company Story section(s), reused {reused} unchanged, to {DATA_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
